UPDATE teams SET 
  slug = 'north-carolina-legal-services',
  name = 'North Carolina Legal Services',
  config = '{"aiModel":"llama","consultationFee":75,"requiresPayment":true,"ownerEmail":"paulchrisluke@gmail.com","availableServices":["Family Law","Small Business and Nonprofits","Employment Law","Tenant Rights Law","Probate and Estate Planning","Special Education and IEP Advocacy"],"domain":"northcarolinalegalservices.blawby.com","description":"Affordable, comprehensive legal services for North Carolina. Family Law, Small Business, Employment, Tenant Rights, Probate, Special Education, and more.","paymentLink":"https://app.blawby.com/northcarolinalegalservices/pay?amount=7500","brandColor":"#059669","accentColor":"#10b981","introMessage":"Welcome to North Carolina Legal Services! I''m here to help you with affordable legal assistance in areas including Family Law, Small Business, Employment, Tenant Rights, Probate, and Special Education. I can answer your questions and help you connect with our experienced attorneys. How can I assist you today?","profileImage":"https://app.blawby.com/storage/team-photos/uCVk3tFuy4aTdR4ad18ibmUn4nOiVY8q4WBgYk1j.jpg"}'
WHERE id = '01jq70jnstyfzevc6423czh50e';

UPDATE teams SET 
  slug = 'blawby-ai',
  name = 'Blawby AI',
  config = '{"aiModel":"llama","consultationFee":0,"requiresPayment":false,"ownerEmail":"paulchrisluke@gmail.com","availableServices":["Business Law","Contract Review","Intellectual Property","Employment Law","General Consultation"],"serviceQuestions":{"Business Law":["What type of business entity are you operating or planning to start?","What specific legal issue are you facing with your business?","Are you dealing with contracts, employment issues, or regulatory compliance?","What is the size and scope of your business operations?"],"Contract Review":["What type of contract do you need reviewed?","What is the value or importance of this contract?","Are there any specific concerns or red flags you''ve noticed?","What is the timeline for this contract?"],"Intellectual Property":["What type of intellectual property are you dealing with?","Are you looking to protect, license, or enforce IP rights?","What is the nature of your IP (patent, trademark, copyright, trade secret)?","What is the commercial value or importance of this IP?"],"Employment Law":["What specific employment issue are you facing?","Are you an employer or employee in this situation?","Have you taken any steps to address this issue?","What is the timeline or urgency of your situation?"],"General Consultation":["Thanks for reaching out! I''d love to help. Can you tell me what legal situation you''re dealing with?","Have you been able to take any steps to address this yet?","What would a good outcome look like for you?","Do you have any documents or information that might be relevant?"]},"domain":"ai.blawby.com","description":"AI-powered legal assistance for businesses and individuals","paymentLink":null,"brandColor":"#2563eb","accentColor":"#3b82f6","introMessage":"Hello! I''m Blawby AI, your intelligent legal assistant. I can help you with business law, contract review, intellectual property, employment law, and general legal consultation. How can I assist you today?","profileImage":null,"blawbyApi":{"enabled":false,"apiUrl":"https://staging.blawby.com"}}'
WHERE id = '01K0TNGNKTM4Q0AG0XF0A8ST0Q'; 