import { FunctionalComponent } from 'preact';
import { ExclamationTriangleIcon } from '@heroicons/react/24/outline';
import { analyzeMissingInfo } from '../utils/matterAnalysis';

interface MatterCanvasProps {
  matterId?: string;
  matterNumber?: string;
  service: string;
  matterSummary: string;
  
  answers: Record<string, string | { question: string; answer: string }>;
}

/**
 * Case Summary component - displays matter details with missing information analysis
 * Shows markdown content with professional matter tracking
 */
const MatterCanvas: FunctionalComponent<MatterCanvasProps> = ({
  matterId,
  matterNumber,
  service,
  matterSummary,
  
  answers
}) => {


  // Generate markdown content for the matter - CLIENT-FACING ONLY
  const generateMarkdown = () => {
    // Only show the matter summary that was generated by AI for the client
    // No internal metrics, scores, or assessments
    return matterSummary;
  };

  const markdownContent = generateMarkdown();
  const missingInfo = analyzeMissingInfo({
    service,
    matterSummary,
    status: 'ready' as const
  });

  return (
    <div class="matter-canvas">
      <div class="matter-canvas-content">
        <pre class="matter-canvas-markdown">
          {markdownContent}
        </pre>
        
        {/* Show missing information */}
        {missingInfo.length > 0 && (
          <div class="missing-info-section">
            <div class="missing-info-header">
              <ExclamationTriangleIcon className="w-4 h-4" />
              <span>Missing Information</span>
            </div>
            <div class="missing-info-list">
              <p>To strengthen your matter, consider providing:</p>
              <ul>
                {missingInfo.map((info, index) => (
                  <li key={index}>{info}</li>
                ))}
              </ul>
              <p class="missing-info-note">
                You can provide this information by continuing our conversation. 
                The more details you share, the better we can assist you.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default MatterCanvas; 